#!/bin/sh
#  ___ _(_) /_    ___  __ __/ / /   ___ _/ / /
# / _ `/ / __/===/ _ \/ // / / /===/ _ `/ / /
# \_, /_/\__/   / .__/\_,_/_/_/    \_,_/_/_/
#/___/         /_/
# Pull all git repos inside ~/repos/ and the ~/.dotfiles/ repo
#  Drew O'Malley
for repo in ~/repos/* ~/.dotfiles; do
	if [ -d "$repo/.git/" ];
	then
		cd $repo
		echo [${PWD##*/}]
		git -c color.ui=always pull | sed 's/^/\t/g'
		git -c color.ui=always status --short --branch | sed 's/^/\t/g'
	fi
done
